-- vim.cmd("colorscheme eldritch")
-- vim.cmd("colorscheme rose-pine")
-- vim.cmd("colorscheme gruvbox")
-- vim.cmd("colorscheme kanagawa")
vim.cmd("colorscheme solarized-osaka")
-- vim.cmd("colorscheme tokyonight")
-- vim.cmd("colorscheme catppuccin")

vim.api.nvim_set_hl(0, "TelescopePromptNormal", { bg = "none" })
vim.api.nvim_set_hl(0, "TelescopeResultsNormal", { bg = "none" })
vim.api.nvim_set_hl(0, "TelescopePreviewNormal", { bg = "none" })

-- Border and Title (optional, for aesthetic consistency)
vim.api.nvim_set_hl(0, "TelescopePromptBorder", { bg = "none" })
vim.api.nvim_set_hl(0, "TelescopeResultsBorder", { bg = "none" })
vim.api.nvim_set_hl(0, "TelescopePreviewBorder", { bg = "none" })
vim.api.nvim_set_hl(0, "TelescopeNormal", { bg = "none" })
vim.api.nvim_set_hl(0, "TelescopeBorder", { bg = "none" })
vim.api.nvim_set_hl(0, "NvimTreeNormal", { bg = "none" })
vim.api.nvim_set_hl(0, "NvimTreeNormalNC", { bg = "none" })
